'use client'

import { useRouter, usePathname } from 'next/navigation'
import { useShopStore } from '@/lib/store'

export function useShopRouter() {
  const router = useRouter()
  const pathname = usePathname()
  const { setSelectedCategoryId, setSelectedProduct, setSearchQuery, setLastOrderId } = useShopStore()

  return {
    pathname,
    goHome: () => router.push('/'),
    goCategory: (categoryId?: string, slug?: string) => {
      if (categoryId) setSelectedCategoryId(categoryId)
      if (slug) {
        router.push(`/category/${slug}`)
      } else {
        router.push('/category')
      }
    },
    goProduct: (productId: string) => router.push(`/product/${productId}`),
    goSearch: (query?: string) => {
      if (query) setSearchQuery(query)
      router.push('/search')
    },
    goCart: () => router.push('/cart'),
    goCheckout: () => router.push('/checkout'),
    goWishlist: () => router.push('/wishlist'),
    goProfile: () => router.push('/profile'),
    goOrders: () => router.push('/orders'),
    goOrderDetail: (orderId: string) => router.push(`/orders/${orderId}`),
    goInvoice: (orderId: string) => router.push(`/invoice/${orderId}`),
    goDeals: () => router.push('/deals'),
    goSettings: () => router.push('/settings'),
    goRewards: () => router.push('/rewards'),
    goAbout: () => router.push('/about'),
    goContact: () => router.push('/contact'),
    goTerms: () => router.push('/terms'),
    goPrivacy: () => router.push('/privacy'),
    goBrands: () => router.push('/brands'),
    goLuxury: () => router.push('/luxury'),
    goRecentlyViewed: () => router.push('/recently-viewed'),
    goCompare: () => router.push('/compare'),
    goGiftCards: () => router.push('/gift-cards'),
    goReferrals: () => router.push('/referrals'),
    goNotifications: () => router.push('/notifications'),
    goStores: () => router.push('/stores'),
    goPriceAlerts: () => router.push('/price-alerts'),
    goWallet: () => router.push('/wallet'),
    goAuctions: () => router.push('/auctions'),
    goSpinWin: () => router.push('/spin-win'),
    goCollections: () => router.push('/collections'),
    goCollectionDetail: (id: string) => router.push(`/collections/${id}`),
    goBlog: () => router.push('/blog'),
    goBlogPost: (slug: string) => router.push(`/blog/${slug}`),
    goHelp: () => router.push('/help'),
    goReturns: () => router.push('/returns'),
    goTrack: (trackingNumber?: string) => router.push(trackingNumber ? `/track?q=${trackingNumber}` : '/track'),
    goVoucher: () => router.push('/voucher'),
    goVip: () => router.push('/vip'),
    goFaq: () => router.push('/faq'),
    goLive: () => router.push('/live'),
    goReviews: () => router.push('/reviews'),
    goFlashSale: () => router.push('/flash-sale'),
    goBundles: () => router.push('/bundles'),
    goSeasonal: () => router.push('/seasonal'),
    goCommunity: () => router.push('/community'),
    goAffiliate: () => router.push('/affiliate'),
    goWishboard: () => router.push('/wishboard'),
    goStyleGuide: () => router.push('/style-guide'),
    goAccessibility: () => router.push('/accessibility'),
    goCookies: () => router.push('/cookies'),
    goSitemap: () => router.push('/sitemap'),
    goVerifyAge: () => router.push('/verify-age'),
    goProductVideos: () => router.push('/product-videos'),
    goGroupBuy: () => router.push('/group-buy'),
    goTradeIn: () => router.push('/trade-in'),
    goInstallment: () => router.push('/installment'),
    goSellerCenter: () => router.push('/seller-center'),
    goDigitalDownloads: () => router.push('/digital-downloads'),
    goProductQuiz: () => router.push('/product-quiz'),
    goLoyaltyCalculator: () => router.push('/loyalty-calculator'),
    goShippingCalculator: () => router.push('/shipping-calculator'),
    goStorePickup: () => router.push('/store-pickup'),
    goOutfitMaker: () => router.push('/outfit-maker'),
    goEmailSubscribe: () => router.push('/email-subscribe'),
    goSellerProfile: (slug: string) => router.push(`/seller-profile?slug=${slug}`),
    goOrderTracking: (orderId?: string) => router.push(orderId ? `/order-tracking?id=${orderId}` : '/order-tracking'),
    goMysteryBox: () => router.push('/mystery-box'),
    goPreorder: () => router.push('/preorder'),
    goGiftRegistry: () => router.push('/gift-registry'),
    goEcoShop: () => router.push('/eco-shop'),
    goPriceMatch: () => router.push('/price-match'),
    goDealCalendar: () => router.push('/deal-calendar'),
    goStockNotifications: () => router.push('/stock-notifications'),
    goProductConfigurator: (productId?: string) => router.push(productId ? `/product-configurator?id=${productId}` : '/product-configurator'),
    goCustomerPhotos: (productId?: string) => router.push(productId ? `/customer-photos?productId=${productId}` : '/customer-photos'),
    goSellerOnboarding: () => router.push('/seller-onboarding'),
    goTryBeforeBuy: () => router.push('/try-before-buy'),
    goPriceDrop: () => router.push('/price-drop'),
    goLoyaltyMall: () => router.push('/loyalty-mall'),
    goGiftWrapping: () => router.push('/gift-wrapping'),
    goWarrantyCenter: () => router.push('/warranty-center'),
    goCharityShop: () => router.push('/charity-shop'),
    goRental: () => router.push('/rental'),
    goStudentDiscount: () => router.push('/student-discount'),
    goPriceGuarantee: () => router.push('/price-guarantee'),
    goReviewMegaphone: () => router.push('/review-megaphone'),
    goMysteryReward: () => router.push('/mystery-reward'),
    goDarkStore: () => router.push('/dark-store'),
    goOrderSuccess: (orderId?: string) => {
      if (orderId) setLastOrderId(orderId)
      router.push(orderId ? `/order-success?id=${orderId}` : '/order-success')
    },
    goFeatures: () => router.push('/features'),
    goPriceDropRefund: () => router.push('/price-drop-refund'),
    goAutoCoupon: () => router.push('/auto-coupon'),
    goRecipeToCart: () => router.push('/recipe-to-cart'),
    goIngredientScanner: () => router.push('/ingredient-scanner'),
    goMedicineTracker: () => router.push('/medicine-tracker'),
    goPetSupplies: () => router.push('/pet-supplies'),
    goApplianceRepair: () => router.push('/appliance-repair'),
    goSubscriptionAudit: () => router.push('/subscription-audit'),
    goTaxRefund: () => router.push('/tax-refund'),
    goVehicleService: () => router.push('/vehicle-service'),
    goDocumentExpiry: () => router.push('/document-expiry'),
    goMovingKit: () => router.push('/moving-kit'),
    goSchoolSupplies: () => router.push('/school-supplies'),
    goDiabeticScanner: () => router.push('/diabetic-scanner'),
    goHalalChecker: () => router.push('/halal-checker'),
    goUnitPriceCalculator: () => router.push('/unit-price-calculator'),
    goCrowdWisdom: () => router.push('/crowd-wisdom'),
    goVideoVerification: () => router.push('/video-verification'),
    goPriceLock: () => router.push('/price-lock'),
    goBulkBuy: () => router.push('/bulk-buy'),
    goProductLiquidator: () => router.push('/product-liquidator'),
    goGroceryListImport: () => router.push('/grocery-list-import'),
    goPrescriptionScan: () => router.push('/prescription-scan'),
    goSafetyRecall: () => router.push('/safety-recall'),
    goMedicineInteraction: () => router.push('/medicine-interaction'),
    goExpiryGuarantee: () => router.push('/expiry-guarantee'),
    goAlternativeFinder: () => router.push('/alternative-finder'),
    goUseCaseMatcher: () => router.push('/use-case-matcher'),
    goTipCalculator: () => router.push('/tip-calculator'),
    goInstallmentCompare: () => router.push('/installment-compare'),
    goMeasurementConverter: () => router.push('/measurement-converter'),
    goSeasonalClothing: () => router.push('/seasonal-clothing'),
    goSmartReorder: () => router.push('/smart-reorder'),
    goFlashbackDeals: () => router.push('/flashback-deals'),
    goDiscountStacking: () => router.push('/discount-stacking'),
    goResaleCalculator: () => router.push('/resale-calculator'),
    goEMICalculator: () => router.push('/emi-calculator'),
    goDealAuthenticity: () => router.push('/deal-authenticity'),
    goSpecCompare: () => router.push('/spec-compare'),
    goFuelCostCalculator: () => router.push('/fuel-cost-calculator'),
    goCurrencyConverter: () => router.push('/currency-converter'),
    goInsuranceClaim: () => router.push('/insurance-claim'),
    goAllergyChecker: () => router.push('/allergy-checker'),
    goChildGrowth: () => router.push('/child-growth'),
    goSeniorMode: () => router.push('/senior-mode'),
    goStudentBudget: () => router.push('/student-budget'),
    goVisualImpaired: () => router.push('/visual-impaired'),
    goEmergencyQuickBuy: () => router.push('/emergency-quick-buy'),
    goClipboardPurchase: () => router.push('/clipboard-purchase'),
    goShoppingListAutocomplete: () => router.push('/shopping-list-autocomplete'),
    goSMSOrder: () => router.push('/sms-order'),
    goUSSDMenu: () => router.push('/ussd-menu'),
    goWhatsAppBulk: () => router.push('/whatsapp-bulk'),
    goPriceEstimator: () => router.push('/price-estimator'),
    goWarrantyExpiry: () => router.push('/warranty-expiry'),
    goAssemblyFinder: () => router.push('/assembly-finder'),
    goIngredientSwap: () => router.push('/ingredient-swap'),
    goProjectPlanner: () => router.push('/project-planner'),
    goGiftMatcher: () => router.push('/gift-matcher'),
    goStyleQuiz: () => router.push('/style-quiz'),
    goBodyType: () => router.push('/body-type'),
    goColorAdvisor: () => router.push('/color-advisor'),
    goTrendForecaster: () => router.push('/trend-forecaster'),
    goSizePredictor: () => router.push('/size-predictor'),
    goWardrobePlanner: () => router.push('/wardrobe-planner'),
    goEventStylist: () => router.push('/event-stylist'),
    goSustainableFinder: () => router.push('/sustainable-finder'),
    goCarbonCalculator: () => router.push('/carbon-calculator'),
    goResumeBuilder: () => router.push('/resume-builder'),
    goLegalDocuments: () => router.push('/legal-documents'),
    goFormBuilder: () => router.push('/form-builder'),
    goScheduler: () => router.push('/scheduler'),
    goServiceConfigurator: () => router.push('/service-configurator'),
    goServiceBlueprint: () => router.push('/service-blueprint'),
    goProjectDashboard: () => router.push('/project-dashboard'),
    goMilestones: () => router.push('/milestones'),
    goRevisionTokens: () => router.push('/revision-tokens'),
    goScopeChange: () => router.push('/scope-change'),
    goHandoffPortal: () => router.push('/handoff-portal'),
    goHealthMonitor: () => router.push('/health-monitor'),
    goAIScoper: () => router.push('/ai-scoper'),
    goAICompetitor: () => router.push('/ai-competitor'),
    goAIPreview: () => router.push('/ai-preview'),
    goAIProposal: () => router.push('/ai-proposal'),
    goAIChatbot: () => router.push('/ai-chatbot'),
    goSmartUpsell: () => router.push('/smart-upsell'),
    goDeadlinePredictor: () => router.push('/deadline-predictor'),
    goQualityCertificate: () => router.push('/quality-certificate'),
    goPortfolioProof: () => router.push('/portfolio-proof'),
    goGuaranteeVault: () => router.push('/guarantee-vault'),
    goDisputeResolution: () => router.push('/dispute-resolution'),
    goSLAGenerator: () => router.push('/sla-generator'),
    goServiceSubscriptions: () => router.push('/service-subscriptions'),
    goReferralSystem: () => router.push('/referral-system'),
    goLoyaltyTiers: () => router.push('/loyalty-tiers'),
    goCorporateCredit: () => router.push('/corporate-credit'),
    goFreeAudit: () => router.push('/free-audit'),
    goROICalculator: () => router.push('/roi-calculator'),
    goCaseStudies: () => router.push('/case-studies'),
    goFreeSample: () => router.push('/free-sample'),
    goCommandCenter: () => router.push('/command-center'),
    goQBRReports: () => router.push('/qbr-reports'),
    goClientCommunity: () => router.push('/client-community'),
    goProfitability: () => router.push('/profitability'),
    goClientLTV: () => router.push('/client-ltv'),
    goDemandForecast: () => router.push('/demand-forecast'),
    goChurnPrediction: () => router.push('/churn-prediction'),
    goPricingTest: () => router.push('/pricing-test'),
    goTemplates: () => router.push('/templates'),
    goUIKits: () => router.push('/ui-kits'),
    goSnippets: () => router.push('/snippets'),
    goGuides: () => router.push('/guides'),
    goCourses: () => router.push('/courses'),
    goAITools: () => router.push('/ai-tools'),
    goAudits: () => router.push('/audits'),
    goSubscriptions: () => router.push('/subscriptions'),
    goDigitalProducts: () => router.push('/digital'),
    goCertifications: () => router.push('/certifications'),
    goEnvSetup: () => router.push('/env-setup'),
    goDatabaseSchemas: () => router.push('/database-schemas'),
    goCICD: () => router.push('/cicd'),
    goNotionTemplates: () => router.push('/notion-templates'),
    goShortTutorials: () => router.push('/short-tutorials'),
    goBack: () => router.back(),
  }
}
