// @ts-nocheck
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

// GET - Get thank you video for order
export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url)
    const orderId = searchParams.get('orderId')

    if (!orderId) {
      return NextResponse.json({ error: 'Order ID required' }, { status: 400 })
    }

    const order = await prisma.order.findUnique({
      where: { id: orderId },
      include: {
        items: {
          include: { 
            product: {
              include: { seller: true }
            }
          }
        }
      }
    })

    if (!order) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 })
    }

    // Get first seller
    const seller = order.items[0]?.product?.seller
    
    if (!seller) {
      return NextResponse.json({ hasVideo: false })
    }

    // Check if seller has thank you video feature enabled
    const video = await prisma.thankYouVideo.findFirst({
      where: {
        orderId,
        sellerId: seller.id
      }
    })

    if (!video) {
      // Auto-generate placeholder (in real app, seller would record)
      return NextResponse.json({
        hasVideo: true,
        video: {
          sellerName: seller.name,
          sellerAvatar: seller.avatar,
          message: `Hi there! Thank you so much for your order. I'm ${seller.name}, and I wanted to personally thank you for supporting my store. I hope you love your purchase!`,
          isAutoGenerated: true,
          duration: 10
        }
      })
    }

    return NextResponse.json({
      hasVideo: true,
      video: {
        url: video.videoUrl,
        sellerName: seller.name,
        sellerAvatar: seller.avatar,
        message: video.message,
        isAutoGenerated: false,
        duration: video.duration
      }
    })
  } catch (error) {
    console.error('Thank you video error:', error)
    return NextResponse.json({ error: 'Failed' }, { status: 500 })
  }
}

// POST - Seller records thank you video
export async function POST(req: NextRequest) {
  try {
    const sellerId = req.headers.get('x-seller-id')
    if (!sellerId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { orderId, videoUrl, message } = await req.json()

    const video = await prisma.thankYouVideo.create({
      data: {
        orderId,
        sellerId,
        videoUrl,
        message,
        duration: 10,
        createdAt: new Date()
      }
    })

    return NextResponse.json({
      success: true,
      video,
      message: 'Thank you video recorded and sent to customer!'
    })
  } catch (error) {
    console.error('Video recording error:', error)
    return NextResponse.json({ error: 'Failed' }, { status: 500 })
  }
}
