-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Category" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT,
    "icon" TEXT,
    "iconSvg" TEXT,
    "iconLottie" TEXT,
    "iconType" TEXT NOT NULL DEFAULT 'icon',
    "imageUrl" TEXT,
    "bannerUrl" TEXT,
    "mobileBannerUrl" TEXT,
    "color" TEXT,
    "gradient" TEXT,
    "textColor" TEXT,
    "order" INTEGER NOT NULL DEFAULT 0,
    "isFeatured" BOOLEAN NOT NULL DEFAULT false,
    "showInMenu" BOOLEAN NOT NULL DEFAULT true,
    "parentId" TEXT,
    "metaTitle" TEXT,
    "metaDescription" TEXT,
    "keywords" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Category_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "Category" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_Category" ("bannerUrl", "color", "createdAt", "description", "icon", "id", "imageUrl", "isActive", "name", "order", "parentId", "slug", "updatedAt") SELECT "bannerUrl", "color", "createdAt", "description", "icon", "id", "imageUrl", "isActive", "name", "order", "parentId", "slug", "updatedAt" FROM "Category";
DROP TABLE "Category";
ALTER TABLE "new_Category" RENAME TO "Category";
CREATE UNIQUE INDEX "Category_slug_key" ON "Category"("slug");
CREATE TABLE "new_Product" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "price" REAL NOT NULL,
    "comparePrice" REAL,
    "categoryId" TEXT NOT NULL,
    "imageUrl" TEXT,
    "images" TEXT,
    "features" TEXT,
    "techStack" TEXT,
    "deliveryTime" TEXT,
    "isFeatured" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isNew" BOOLEAN NOT NULL DEFAULT false,
    "isTrending" BOOLEAN NOT NULL DEFAULT false,
    "isFlashDeal" BOOLEAN NOT NULL DEFAULT false,
    "flashExpiresAt" DATETIME,
    "isVIPOnly" BOOLEAN NOT NULL DEFAULT false,
    "isLuxury" BOOLEAN NOT NULL DEFAULT false,
    "isOnSale" BOOLEAN NOT NULL DEFAULT false,
    "isMock" BOOLEAN NOT NULL DEFAULT false,
    "discount" INTEGER NOT NULL DEFAULT 0,
    "inventory" INTEGER NOT NULL DEFAULT 0,
    "rating" REAL NOT NULL DEFAULT 0,
    "reviewCount" INTEGER NOT NULL DEFAULT 0,
    "views" INTEGER NOT NULL DEFAULT 0,
    "tags" TEXT,
    "order" INTEGER NOT NULL DEFAULT 0,
    "weight" REAL,
    "expiryDate" DATETIME,
    "ingredients" TEXT,
    "stock" INTEGER,
    "color" TEXT,
    "size" TEXT,
    "ecoScore" REAL,
    "carbonFootprint" REAL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "sellerId" TEXT,
    "arModelUrl" TEXT,
    "dimensions" TEXT,
    "qrCode" TEXT,
    "serialNumber" TEXT,
    "isAuthentic" BOOLEAN NOT NULL DEFAULT false,
    "manufacturedAt" DATETIME,
    "batchNumber" TEXT,
    "origin" TEXT,
    "updatedAt" DATETIME NOT NULL,
    "complexity" TEXT NOT NULL DEFAULT 'medium',
    "complexityGuide" TEXT,
    "demoUrl" TEXT,
    "previewImages" TEXT,
    "interactiveDemoUrl" TEXT,
    "videoDemoUrl" TEXT,
    "rushDeliveryAvailable" BOOLEAN NOT NULL DEFAULT false,
    "rushDeliveryPrice" REAL,
    "standardDeliveryDays" INTEGER NOT NULL DEFAULT 14,
    "rushDeliveryDays" INTEGER NOT NULL DEFAULT 3,
    "maxMonthlyOrders" INTEGER NOT NULL DEFAULT 10,
    "currentMonthOrders" INTEGER NOT NULL DEFAULT 0,
    "techStackOptions" TEXT,
    "emiAvailable" BOOLEAN NOT NULL DEFAULT false,
    "emiMinAmount" REAL NOT NULL DEFAULT 5000,
    "svgUrl" TEXT,
    "svgAnimation" TEXT,
    "lottieUrl" TEXT,
    "illustrationCode" TEXT,
    "illustrationType" TEXT,
    "thumbnailType" TEXT NOT NULL DEFAULT 'image',
    "previewUrl" TEXT,
    "videoThumbnail" TEXT,
    "shortDescription" TEXT,
    "badge" TEXT,
    "badgeColor" TEXT,
    "metaTitle" TEXT,
    "metaDescription" TEXT,
    "keywords" TEXT,
    "altText" TEXT,
    "productType" TEXT NOT NULL DEFAULT 'physical',
    "sku" TEXT,
    "barcode" TEXT,
    "taxClass" TEXT,
    "taxRate" REAL,
    "shippingClass" TEXT,
    "downloadUrl" TEXT,
    "downloadLimit" INTEGER,
    "fileSize" TEXT,
    "fileFormat" TEXT,
    "subscriptionPeriod" TEXT,
    "subscriptionPrice" REAL,
    "trialDays" INTEGER,
    "galleryType" TEXT NOT NULL DEFAULT 'grid',
    "galleryColumns" INTEGER NOT NULL DEFAULT 3,
    "relatedProducts" TEXT,
    "crossSells" TEXT,
    "upsells" TEXT,
    "whiteLabelAvailable" BOOLEAN NOT NULL DEFAULT false,
    "whiteLabelPrice" REAL,
    "variants" TEXT,
    "specifications" TEXT,
    "howToUse" TEXT,
    "materials" TEXT,
    "packagingType" TEXT,
    "isRecyclable" BOOLEAN NOT NULL DEFAULT false,
    "isEcoFriendly" BOOLEAN NOT NULL DEFAULT false,
    "totalSales" INTEGER NOT NULL DEFAULT 0,
    "wishlistCount" INTEGER NOT NULL DEFAULT 0,
    "warrantyMonths" INTEGER,
    "returnDays" INTEGER,
    "brand" TEXT,
    "isLocal" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "Product_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Product_sellerId_fkey" FOREIGN KEY ("sellerId") REFERENCES "Seller" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Product_sellerId_fkey" FOREIGN KEY ("sellerId") REFERENCES "Seller" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_Product" ("arModelUrl", "batchNumber", "brand", "carbonFootprint", "categoryId", "color", "comparePrice", "complexity", "complexityGuide", "createdAt", "currentMonthOrders", "deliveryTime", "demoUrl", "description", "dimensions", "discount", "ecoScore", "emiAvailable", "emiMinAmount", "expiryDate", "features", "flashExpiresAt", "howToUse", "id", "imageUrl", "images", "ingredients", "interactiveDemoUrl", "inventory", "isActive", "isAuthentic", "isEcoFriendly", "isFeatured", "isFlashDeal", "isLocal", "isLuxury", "isMock", "isNew", "isOnSale", "isRecyclable", "isTrending", "isVIPOnly", "manufacturedAt", "materials", "maxMonthlyOrders", "name", "order", "origin", "packagingType", "previewImages", "price", "qrCode", "rating", "returnDays", "reviewCount", "rushDeliveryAvailable", "rushDeliveryDays", "rushDeliveryPrice", "sellerId", "serialNumber", "size", "slug", "specifications", "standardDeliveryDays", "stock", "tags", "techStack", "techStackOptions", "totalSales", "updatedAt", "variants", "videoDemoUrl", "views", "warrantyMonths", "weight", "whiteLabelAvailable", "whiteLabelPrice", "wishlistCount") SELECT "arModelUrl", "batchNumber", "brand", "carbonFootprint", "categoryId", "color", "comparePrice", "complexity", "complexityGuide", "createdAt", "currentMonthOrders", "deliveryTime", "demoUrl", "description", "dimensions", "discount", "ecoScore", "emiAvailable", "emiMinAmount", "expiryDate", "features", "flashExpiresAt", "howToUse", "id", "imageUrl", "images", "ingredients", "interactiveDemoUrl", "inventory", "isActive", "isAuthentic", "isEcoFriendly", "isFeatured", "isFlashDeal", "isLocal", "isLuxury", "isMock", "isNew", "isOnSale", "isRecyclable", "isTrending", "isVIPOnly", "manufacturedAt", "materials", "maxMonthlyOrders", "name", "order", "origin", "packagingType", "previewImages", "price", "qrCode", "rating", "returnDays", "reviewCount", "rushDeliveryAvailable", "rushDeliveryDays", "rushDeliveryPrice", "sellerId", "serialNumber", "size", "slug", "specifications", "standardDeliveryDays", "stock", "tags", "techStack", "techStackOptions", "totalSales", "updatedAt", "variants", "videoDemoUrl", "views", "warrantyMonths", "weight", "whiteLabelAvailable", "whiteLabelPrice", "wishlistCount" FROM "Product";
DROP TABLE "Product";
ALTER TABLE "new_Product" RENAME TO "Product";
CREATE UNIQUE INDEX "Product_slug_key" ON "Product"("slug");
CREATE UNIQUE INDEX "Product_qrCode_key" ON "Product"("qrCode");
CREATE UNIQUE INDEX "Product_sku_key" ON "Product"("sku");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
